---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    policy: enforced
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  namespace: app
spec:
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: ghcr.io/rp-thomas/flux-push-poc:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: ghcr-secret