apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml

labels:
  - includeSelectors: false
    includeTemplates: false
    pairs:
      app.kubernetes.io/version: "main-bfd5fe80bb22b30baa09c58436df05c4764cdb4b"
